import { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { getProcurementList } from '../utils/inventory';
import { formatDate } from '../utils/formatters';
import VEGETABLE_DB from '../data/vegetables';
import C from '../theme/colors';
import Card from '../components/Card';
import './ProcurementPage.css';

function ProcurementPage() {
  const { inventory, lang } = useApp();
  const procurement = getProcurementList(inventory);

  const [list, setList] = useState(() => {
    const l = {};
    Object.entries(procurement).forEach(([k, v]) => {
      l[k] = { qty: v, checked: false };
    });
    return l;
  });

  useEffect(() => {
    const newProcurement = getProcurementList(inventory);
    setList(prev => {
      const l = {};
      Object.entries(newProcurement).forEach(([k, v]) => {
        l[k] = { qty: prev[k]?.qty || v, checked: prev[k]?.checked || false };
      });
      return l;
    });
  }, [inventory]);

  const toggle = (key) =>
    setList(prev => ({
      ...prev,
      [key]: { ...prev[key], checked: !prev[key].checked },
    }));

  const total = Object.values(list).filter(v => !v.checked).length;

  const generateText = () => {
    const lines = Object.entries(list)
      .filter(([, v]) => !v.checked)
      .map(
        ([k, v]) =>
          `${VEGETABLE_DB[k]?.icon || ''} ${VEGETABLE_DB[k]?.en || k} \u2014 ${v.qty} ${VEGETABLE_DB[k]?.unit || 'kg'}`
      );
    return `\u{1F6D2} *Viniyoga Shopping List*\n\u{1F4C5} ${formatDate(new Date())}\n\n${lines.join('\n')}\n\n_Generated by Viniyoga_`;
  };

  const handleShare = () => {
    const text = generateText();
    if (navigator.share) {
      navigator.share({ title: 'Shopping List', text });
    } else {
      navigator.clipboard?.writeText(text);
      alert('List copied to clipboard!');
    }
  };

  return (
    <div className="procurement-page">
      <h2 className="procurement-page__title">
        &#x1F6D2; Procurement List
      </h2>
      <p className="procurement-page__subtitle">
        {total} items to buy &middot; Based on threshold alerts
      </p>

      {Object.keys(list).length === 0 ? (
        <Card className="procurement-page__empty">
          <div className="procurement-page__empty-icon">&#x1F389;</div>
          <div className="procurement-page__empty-title">All stocked up!</div>
          <div className="procurement-page__empty-sub">
            No items below threshold
          </div>
        </Card>
      ) : (
        <>
          <div className="procurement-page__list">
            {Object.entries(list).map(([key, val]) => {
              const db = VEGETABLE_DB[key];
              return (
                <Card
                  key={key}
                  onClick={() => toggle(key)}
                  hover
                  className={`procurement-item ${val.checked ? 'procurement-item--checked' : ''}`}
                  style={{
                    padding: '12px 16px',
                    borderLeft: `4px solid ${val.checked ? C.light : C.saffron}`,
                  }}
                >
                  <div className="procurement-item__row">
                    <div className="procurement-item__left">
                      <div
                        className={`procurement-item__checkbox ${val.checked ? 'procurement-item__checkbox--checked' : ''}`}
                      >
                        {val.checked ? '\u2713' : ''}
                      </div>
                      <span className="procurement-item__icon">
                        {db?.icon}
                      </span>
                      <div>
                        <div
                          className={`procurement-item__name ${val.checked ? 'procurement-item__name--checked' : ''}`}
                        >
                          {db?.[lang] || db?.en || key}
                        </div>
                        {lang !== 'en' && (
                          <div className="procurement-item__name-en">
                            {db?.en}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="procurement-item__qty">
                      {val.qty} {db?.unit || 'kg'}
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>

          <button className="procurement-page__share" onClick={handleShare}>
            &#x1F4F2; Share via WhatsApp / Copy List
          </button>
        </>
      )}
    </div>
  );
}

export default ProcurementPage;
